.\" Copyright (c) 2000 Kungliga Tekniska H,Avgskolan
.\" (Royal Institute of Technology, Stockholm, Sweden). 
.\" All rights reserved. 
.\"
.\" Redistribution and use in source and binary forms, with or without 
.\" modification, are permitted provided that the following conditions 
.\" are met: 
.\"
.\" 1. Redistributions of source code must retain the above copyright 
.\"    notice, this list of conditions and the following disclaimer. 
.\"
.\" 2. Redistributions in binary form must reproduce the above copyright 
.\"    notice, this list of conditions and the following disclaimer in the 
.\"    documentation and/or other materials provided with the distribution. 
.\"
.\" 3. Neither the name of the Institute nor the names of its contributors 
.\"    may be used to endorse or promote products derived from this software 
.\"    without specific prior written permission. 
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE INSTITUTE AND CONTRIBUTORS ``AS IS'' AND 
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE INSTITUTE OR CONTRIBUTORS BE LIABLE 
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS 
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY 
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF 
.\" SUCH DAMAGE. 
.\"
.\" $Id: kerberos.8,v 1.1 2004-09-25 07:34:35 metal Exp $
.\"
.\" $FreeBSD$
.\"
.Dd September 1, 2000
.Dt KERBEROS 8
.Os HEIMDAL
.Sh 名称
.Nm kerberos
.Nd Kerberos システムの手引き
.Sh 解説
Kerberos はネットワーク認証システムです。
その目的は安全でないネットワークでユーザとサービスを安全に認証することです。
.Pp
これは、信頼できる第三者として動作し、(まとめて
.Em principal
と呼ばれる) ユーザとサービスすべての秘密鍵のデータベースを保持する
Kerberos サーバで行われます。
.Pp
各 principal はただ 1 つの
.Em realm
に所属します。
realm とは Kerberos での管理領域のことです。
realm はたいてい組織に対応し、普通は組織のドメイン名に由来する名前です。
1 つの realm には、1 つもしくは複数の Kerberos サーバがあります。
.Pp
認証の過程で
.Sq チケット
と
.Sq 認証子
の交換が行われます。
これらはどちらも principal の身分を証明するものです。
.Pp
通常のシステムログインもしくは
.Xr kinit 1
プログラムのどちらかで Kerberos システムにログインする時に、
.Em チケット交付チケット
を取得します。
これによって、
.Ic telnet
や
.Ic ftp
などの他のサービスのための新しいチケットを
パスワードを入力することなく取得できます。
.Pp
Kerberos がどのように動作するかについてのより詳しい情報や
Kerberos に関するその他の一般的な疑問については
.Pa http://www.nrl.navy.mil/CCS/people/kenh/kerberos-faq.html
の the Kerberos FAQ を参照して下さい。
.Pp
セットアップについては、Heimdal Texinfo マニュアルを参照して下さい。
.Sh 関連項目
.Xr ftp 1 ,
.Xr kdestroy 1 ,
.Xr kinit 1 ,
.Xr klist 1 ,
.Xr kpasswd 1 ,
.Xr telnet 1
.Sh 歴史
Kerberos 認証システムは 1980 年代の後半にマサチューセッツ工科大学 (MIT) で
Athena プロジェクトの一環として開発されました。
1 から 3 までのバージョンは MIT 外部に出ることはありませんでしたが、
バージョン 4 は、特に研究者たちによって、かなり一般的に使用されていました
(そして今でも使用されています)。
また、AFS ファイルシステムのような商用製品でも使用されています。
.Pp
バージョン 4 の問題は、多くの制限があること、
(長い間開発されていたので) コードがあまりきれいに書かれていないこと、
たくさんの既知のセキュリティの問題があることです。
この問題の多くを解決するため、バージョン 5 の作業が始められ、
1993 年に IETF RFC1510 という形になりました。
それ以来、多くの開発作業が行われており、うまくいけば間もなく
新しい RFC が出てくるでしょう。
.Pp
このマニュアルページは、1997 年頃からスウェーデンの王立ストックホルム工科大学で
開発されている
.Nm Heimdal
Kerberos 5 ディストリビューションの一部です。
